hide_window_decorations yes
linux_display_server x11

font_size 11
background_opacity 0.94
dynamic_background_opacity yes

confirm_os_window_close 0
enable_audio_bell no
remember_window_size no
initial_window_width 960
initial_window_height 540

placement_strategy top-left
shell_integration enabled
cursor_blink_interval 0
scrollback_lines 5000
window_padding_width 6
